language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  twine_version: 1.15.0
  distributions: sdist bdist_wheel
  user: panagiks
  password:
    secure: W6upk4FfdyMfofuVZ9BgwCqtdjJeDlDuDfPFzs4jnAnSmB5kSJMNiPyK+Omi7xHGDgRLpCBChJ6VCox0ENc0nse4nP+iqW2vOQdnbWL6CXu2OzTcDkswKRuFVpqCcOcJSpUMHQg9LVDij8GVGnzfVqD+eZUp8aLsItn2eQugKVp0Z4re2Y/qDEqjPJQphyEj8KIbiSkishiFdjHyumz4sL7Am0N3+eVXU4+ALUPC3ErBlXxTnYbm4C06vOe4mWDPkm2sKzC3CfspJvrc/4MYUh8Iiv0/RInESzmvR/EqoWOHzly/lZkJcFOaU4MVRFz1mrjggUR27RIrSCZN//weMbMq7O9gnWLY4MmBkDbyB9IE1VlUbcrLgQKXWgq1mbPmcy7qfGsVbYt2MwTDLwjZT+d39Uf/r/HiKwk3BgxcemTMerAqIL2WnYuFXePsq4vvegyfDYTn2sgHDLX9ZOVxo4GYhWeI5KE2vtafrzID91mD2zeFerMOZhAbSb59qPt8+uqt0dk5/M4sYE1oKo931KIKL6/7agJXUDoA4KDlOwhYMj4xNoKq3Wilcu+L0Qd5TQFAd0VpsIhGgrKhV+xUJKtSSsdLcSo8vlCy7XGf4ohJrLXbcA8sPnQbxMDXUmw0KsV5RMccpAM0QlHj5Y18W1D2WkZTam4j3KSu6QMOmwc=
  on:
    tags: true
    repo: panagiks/yaab
    python: 3.6
